[package]
name = "supermutation"
version = "0.1.0"
authors = ["Chris Patuzzo <chris@patuzzo.co.uk>"]
edition = "2018"

[dependencies]
bucket_queue = "2.0.0"
croaring = "0.3.7"
lazy_static = "1.2.0"
lehmer = "3.0.0"
